version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      restart: always
      ports:
        - 8080:8080
      environment:
        - PORT=$PORT
        - DB_NAME=$DB_NAME
        - DB_USER=$DB_USER
        - DB_PASS=$DB_PASS
        - DB_PORT=$DB_PORT
        - SUPA_SECRET:$SUPA_SECRET
        - GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
        - GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
      db:
        image: mysql:8.0
        restart: always
        ports:
          - 3306:3306
        environment: 
          - MYSQL_ROOT_PASSWORD=$DB_PASS
          - MYSQL_DATABASE=$DB_NAME
          - MSQL_USER=$DB_USER
          - MYSQL_PASSWORD=$DB_PASS
        volumes:
          - db_data:/var/lib/mysql
    volumes:
      db_data:
      